/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Auth`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Cart`; params?: Router.UnknownInputParams; } | { pathname: `/Favorites`; params?: Router.UnknownInputParams; } | { pathname: `/Search`; params?: Router.UnknownInputParams; } | { pathname: `/../types/icon.interface`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/bottom-menu/menu-item.interface`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/bottom-menu/MenuBottom`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/bottom-menu/menu-item`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/bottom-menu/MenuItem`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Auth`; params?: Router.UnknownOutputParams; } | { pathname: `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/Cart`; params?: Router.UnknownOutputParams; } | { pathname: `/Favorites`; params?: Router.UnknownOutputParams; } | { pathname: `/Search`; params?: Router.UnknownOutputParams; } | { pathname: `/../types/icon.interface`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/layout/bottom-menu/menu-item.interface`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/layout/bottom-menu/MenuBottom`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/layout/bottom-menu/menu-item`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/layout/bottom-menu/MenuItem`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Auth${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/Cart${`?${string}` | `#${string}` | ''}` | `/Favorites${`?${string}` | `#${string}` | ''}` | `/Search${`?${string}` | `#${string}` | ''}` | `/../types/icon.interface${`?${string}` | `#${string}` | ''}` | `/../components/layout/bottom-menu/menu-item.interface${`?${string}` | `#${string}` | ''}` | `/../components/layout/bottom-menu/MenuBottom${`?${string}` | `#${string}` | ''}` | `/../components/layout/bottom-menu/menu-item${`?${string}` | `#${string}` | ''}` | `/../components/layout/bottom-menu/MenuItem${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Auth`; params?: Router.UnknownInputParams; } | { pathname: `/Home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/Cart`; params?: Router.UnknownInputParams; } | { pathname: `/Favorites`; params?: Router.UnknownInputParams; } | { pathname: `/Search`; params?: Router.UnknownInputParams; } | { pathname: `/../types/icon.interface`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/bottom-menu/menu-item.interface`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/bottom-menu/MenuBottom`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/bottom-menu/menu-item`; params?: Router.UnknownInputParams; } | { pathname: `/../components/layout/bottom-menu/MenuItem`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
